[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = ""
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[deploy.healthcheckPath]
path = "/"

[deploy.healthcheckTimeout]
timeout = 100

# Environment variables
[deploy.env]
PUID = "1000"
PGID = "1000"
TZ = "UTC"
